/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformAdminRouteImport } from './routes/platform-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformAdminIndexRouteImport } from './routes/platform-admin.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PlatformAdminLoginRouteImport } from './routes/platform-admin.login'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppUdhariRouteImport } from './routes/app.udhari'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppDeliveryBoysRouteImport } from './routes/app.delivery-boys'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCashbookRouteImport } from './routes/app.cashbook'
import { Route as AppCustomersIdRouteImport } from './routes/app.customers.$id'

const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/platform-admin',
  path: '/platform-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminIndexRoute = PlatformAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PlatformAdminLoginRoute = PlatformAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppUdhariRoute = AppUdhariRouteImport.update({
  id: '/udhari',
  path: '/udhari',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryBoysRoute = AppDeliveryBoysRouteImport.update({
  id: '/delivery-boys',
  path: '/delivery-boys',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCashbookRoute = AppCashbookRouteImport.update({
  id: '/cashbook',
  path: '/cashbook',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/platform-admin': typeof PlatformAdminRouteWithChildren
  '/app/cashbook': typeof AppCashbookRoute
  '/app/customers': typeof AppCustomersRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery-boys': typeof AppDeliveryBoysRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/products': typeof AppProductsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/udhari': typeof AppUdhariRoute
  '/app/users': typeof AppUsersRoute
  '/platform-admin/login': typeof PlatformAdminLoginRoute
  '/app/': typeof AppIndexRoute
  '/platform-admin/': typeof PlatformAdminIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/cashbook': typeof AppCashbookRoute
  '/app/customers': typeof AppCustomersRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery-boys': typeof AppDeliveryBoysRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/products': typeof AppProductsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/udhari': typeof AppUdhariRoute
  '/app/users': typeof AppUsersRoute
  '/platform-admin/login': typeof PlatformAdminLoginRoute
  '/app': typeof AppIndexRoute
  '/platform-admin': typeof PlatformAdminIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/platform-admin': typeof PlatformAdminRouteWithChildren
  '/app/cashbook': typeof AppCashbookRoute
  '/app/customers': typeof AppCustomersRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery-boys': typeof AppDeliveryBoysRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/products': typeof AppProductsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/udhari': typeof AppUdhariRoute
  '/app/users': typeof AppUsersRoute
  '/platform-admin/login': typeof PlatformAdminLoginRoute
  '/app/': typeof AppIndexRoute
  '/platform-admin/': typeof PlatformAdminIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/platform-admin'
    | '/app/cashbook'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/delivery-boys'
    | '/app/expenses'
    | '/app/payments'
    | '/app/products'
    | '/app/reports'
    | '/app/sales'
    | '/app/udhari'
    | '/app/users'
    | '/platform-admin/login'
    | '/app/'
    | '/platform-admin/'
    | '/app/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/cashbook'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/delivery-boys'
    | '/app/expenses'
    | '/app/payments'
    | '/app/products'
    | '/app/reports'
    | '/app/sales'
    | '/app/udhari'
    | '/app/users'
    | '/platform-admin/login'
    | '/app'
    | '/platform-admin'
    | '/app/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/platform-admin'
    | '/app/cashbook'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/delivery-boys'
    | '/app/expenses'
    | '/app/payments'
    | '/app/products'
    | '/app/reports'
    | '/app/sales'
    | '/app/udhari'
    | '/app/users'
    | '/platform-admin/login'
    | '/app/'
    | '/platform-admin/'
    | '/app/customers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlatformAdminRoute: typeof PlatformAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platform-admin': {
      id: '/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin/': {
      id: '/platform-admin/'
      path: '/'
      fullPath: '/platform-admin/'
      preLoaderRoute: typeof PlatformAdminIndexRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/platform-admin/login': {
      id: '/platform-admin/login'
      path: '/login'
      fullPath: '/platform-admin/login'
      preLoaderRoute: typeof PlatformAdminLoginRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/udhari': {
      id: '/app/udhari'
      path: '/udhari'
      fullPath: '/app/udhari'
      preLoaderRoute: typeof AppUdhariRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/delivery-boys': {
      id: '/app/delivery-boys'
      path: '/delivery-boys'
      fullPath: '/app/delivery-boys'
      preLoaderRoute: typeof AppDeliveryBoysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cashbook': {
      id: '/app/cashbook'
      path: '/cashbook'
      fullPath: '/app/cashbook'
      preLoaderRoute: typeof AppCashbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/$id': {
      id: '/app/customers/$id'
      path: '/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
  }
}

interface AppCustomersRouteChildren {
  AppCustomersIdRoute: typeof AppCustomersIdRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersIdRoute: AppCustomersIdRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppRouteChildren {
  AppCashbookRoute: typeof AppCashbookRoute
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliveryBoysRoute: typeof AppDeliveryBoysRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppUdhariRoute: typeof AppUdhariRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCashbookRoute: AppCashbookRoute,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDeliveryBoysRoute: AppDeliveryBoysRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProductsRoute: AppProductsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppUdhariRoute: AppUdhariRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlatformAdminRouteChildren {
  PlatformAdminLoginRoute: typeof PlatformAdminLoginRoute
  PlatformAdminIndexRoute: typeof PlatformAdminIndexRoute
}

const PlatformAdminRouteChildren: PlatformAdminRouteChildren = {
  PlatformAdminLoginRoute: PlatformAdminLoginRoute,
  PlatformAdminIndexRoute: PlatformAdminIndexRoute,
}

const PlatformAdminRouteWithChildren = PlatformAdminRoute._addFileChildren(
  PlatformAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlatformAdminRoute: PlatformAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
